### PR TITLE
Creating FOSDEM 2017 Open Source Design track event

### PR DESCRIPTION
**Pull request by evalica**

### CODE REVIEW

**Comment by evalica** [comment]
- Event dates need to be fixed when we find them out
- I've kept 20min presentation (see if we change that - depending on the number of submissions)
- I've let 1 Dec the deadline for accepting proposals (the hard deadline is 11 Dec) - we can extend if needed

**Comment by belenbarrospena** [comment]
This looks good to me. Thanks @evalica

**Comment by evalica** [comment]
@belenbarrospena Thanks for reviewing

**Comment by evalica** [comment]
Not really sure why the website is not updated with the events.

**Comment by belenbarrospena** [comment]
Mmmm, yes, the page returns 404. I wonder if it's related somehow to the date format. The raw file has

```
#### Submission deadline:

~~1st December 2016~~
```

And the markup preview shows it as striked through text, like so

#### Submission deadline:

~~1st December 2016~~

https://github.com/opensourcedesign/events/blob/48c8f9f57d4983455fdce9a2c764bc80d334d424/_posts/%20%202017-02-04-opensourcedesign-fosdem.markdown

Maybe Jekyll is not liking that? Other than that, I can't see anything strange in the file :/

**Comment by belenbarrospena** [comment]
Also, we have a date now: Sunday 5th

https://fosdem.org/2017/news/2016-10-10-accepted-developer-rooms/?utm_source=twitterfeed&utm_medium=twitter

**Pull request merged**
