### PR TITLE
Adding AGPL-3.0 License

### PR DESCRIPTION
**Pull request by irazirfan**
@jancborchardt 
@evalica 
@ei8fdb 
@bnvk

### CODE REVIEW

**Review by vinitshahdeo — APPROVED** [review]

**Comment by irazirfan** [comment]
@skddc @pfefferle @garrett 
please review this

**Comment by belenbarrospena** [comment]
Hi @irazirfan 

Thanks for the PR. When it comes to adding a license, I would expect a bit of an explanation as to why that specific license was chosen.  

Could you please tell us a bit about why you've chosen AGPL-3.0?

Thanks!

**Review by belenbarrospena — COMMENTED** [review]
I am not sure what's the purpose of the second patch. It seems to just add the license file, like the first one.

**Comment by irazirfan** [comment]
> I am not sure what's the purpose of the second patch. It seems to just add the license file, like the first one.

that's because the license was created in a separate branch!

**Comment by irazirfan** [comment]
> Hi @irazirfan
> 
> Thanks for the PR. When it comes to adding a license, I would expect a bit of an explanation as to why that specific license was chosen.
> 
> Could you please tell us a bit about why you've chosen AGPL-3.0?
> 
> Thanks!

In jobs repository this AGPL license has been used, that's why I think it'd be appropriate here also.
https://github.com/opensourcedesign/jobs

**Comment by belenbarrospena** [comment]
> In jobs repository this AGPL license has been used,

Hehehe. That sounds like a fairly good reason :)

About the 2 patches, I still think it would be better to have a clean PR with a single patch adding the license file, but it would be good to hear what someone with more git experience has to say.

**Review by jancborchardt — APPROVED** [review]
Looks good, and AGPLv3+ is also the proper license. :)

**Pull request merged**
