### PR TITLE
Create Basic Readme.md

### PR DESCRIPTION
**Pull request by simonv3**

### CODE REVIEW

**Comment by jancborchardt** [comment]
The previous master branch had a readme with nice parts, we could take that: https://github.com/opensourcedesign/events/tree/64f814c702e1b098b0bd11769f419dfcfc053527

**Comment by simonv3** [comment]
@jancborchardt heh, that means I'll have to pull down the repo (instead of just creating it all via github). That'll take a bit of mindset shift so I'll redo this later.

**Comment by jancborchardt** [comment]
@simonv3 nah, just copy the relevant text from there. :)

**Comment by simonv3** [comment]
@jancborchardt Can I still make those changes once I've submitted the PR?

Edit: the answer is apparently yes!

**Comment by jancborchardt** [comment]
Yup :) I’d remove the Past and Current events sections though, and just link to http://opensourcedesign.net/events/ in the description.

**Comment by simonv3** [comment]
@jancborchardt ping :)

**Comment by jancborchardt** [comment]
:+1: :)

**Pull request merged**
