### PR TITLE
[Bug] Broken location URL

### PR DESCRIPTION
**Pull request by evalica**
The second Jitsi URL is broken, maybe because there is a different mechanism to add that table information. 

I've removed the link and kept only "Online", but there is some duplication on this page. 
Not really sure what is the best solution.

url

### CODE REVIEW

**Comment by ei8fdb** [comment]
@evalica Yes! I was trying to figure out where the duplication is coming from. It's not in the .md file as far as I can see...

It would be good to have the link in it, however if it's broken I agree about removing it.

**Review by ei8fdb — APPROVED** [review]

**Comment by jancborchardt** [comment]
I’d say change the "location" to only "https://meet.jit.si/opensourcedesign", and then cut the bottom part instead with »Date & location« and »our next event is …«

Because these infos are now automatically read from the header.

**Comment by evalica** [comment]
Maybe something like: 
proposal

The issues with this proposal: 
- It's not looking very good
- I don't think we can have links inside our header, so it will be harder to click.

**Comment by evalica** [comment]
How about?
proposal 2

**Comment by ei8fdb** [comment]
Why is the link formatting not working? I am not able to figure this out. Is it a hard/easy fix?

**Comment by evalica** [comment]
I don't know Bernard :) maybe it will work, but I looked at other events and we don't have links in them. It was initially made to hold text information. Not sure where to look to fix it.

**Comment by ei8fdb** [comment]
Ahhhh...ok. ;) I wasn't sure if it was me being slow.

How about ^^^^^

**Comment by jancborchardt** [comment]
Alright, looking good! I now also removed the "Date & Location" block below, because as said that is added by the template itself, generated out of the info of the header. :)

**Review by jancborchardt — APPROVED** [review]

**Comment by jancborchardt** [comment]
Looks great at http://opensourcedesign.net/events/open-source-design-monthly-online-meeting/ :)

**Comment by jancborchardt** [comment]
Looks great at http://opensourcedesign.net/events/open-source-design-monthly-online-meeting/ :)

**Comment by ei8fdb** [comment]
Ahh the duplication is because of the template.!

**Pull request merged**
