### PR TITLE
Add LG-track at SCaLE

### PR DESCRIPTION
**Pull request by patdavid**
Adding the upcoming Libre Graphics track at SCaLE (and the assocaited CFP).

### CODE REVIEW

**Comment by patdavid** [comment]
If anyone gets a moment and can do a quick review, that'd be _awesome_. :)

**Review by simonv3 — APPROVED** [review]
LGTM!

**Comment by jancborchardt** [comment]
@patdavid that's so cool! Design tracks all around at free & open source conferences! :tada:

**Comment by patdavid** [comment]
Yeah, it's exciting!  If anyone from the OS Design community here can make it out and wants to present (or just get together), please don't hesitate to reach out and let me know!

**Pull request merged**
