### PR TITLE
Add filter ability for upcoming and past events

### PR DESCRIPTION
**Pull request by Xaviju**
Added a new attribute for the events, it could be either 'upcoming' or 'past'
If 'upcoming' shows title, excerpt, date, location..etc.
If 'past' shows only title and excerpt (i think it gives a basic information but we should be careful with the excerpt)

If no upcoming shows how to add an event.

### CODE REVIEW

**Comment by simonv3** [comment]
Thanks for the PR @Xaviju.

I wonder though - wouldn't it be better (less duplicate data) to just standardize the date as whatever the ISO format is (dd-mm-yyyy I think) and then filter based on before or after that date?

**Comment by Xaviju** [comment]
@simonv3 
I tried to do that, but didn't find how to convert the eventDate string to a date format and compare it. The post date is not a good reference because its the published date, not the event date.

If do you know how to do that I'll be happy to fix the PR

**Comment by simonv3** [comment]
Hey @Xaviju, sorry to keep you waiting. I'll have a look at how to do filtering this weekend, for now this will do though.

**Comment by Xaviju** [comment]
@simonv3 thanks for merging!

**Pull request merged**
