### PR TITLE
Add past status to Berlin meetup

### PR DESCRIPTION
**Pull request by jancborchardt**
The status needs to be either »upcoming« or »past«. :)

@jdittrich @Incabell @HeikoTietze do we have a date for the next meetup already so we can add and promote it earlier?

### CODE REVIEW

**Comment by jdittrich** [comment]
> @jdittrich @Incabell @HeikoTietze do we have a date for the next meetup already so we can add and promote it earlier?

Wouldn't this be the 26th of May after the [Open Tech Summit](http://opentechsummit.net/)? Or was that thought as an additional meeting?  (asking @elioqoshi …)

**Comment by jancborchardt** [comment]
Yeah, let's just do that as next meetup then! :)

**Comment by elioqoshi** [comment]
Sorry, didn't get it? Anything I need to do here?

**Comment by jancborchardt** [comment]
@elioqoshi it's just about the meetup you proposed on Twitter on the day after OpenTechSummit. ;) As soon as the date is fixed, simply put it on here. :)

**Comment by elioqoshi** [comment]
The date is fixed as that's the only date I'm available (if it's a meetup where I would be that is). Which time did you do it last time?

**Comment by jancborchardt** [comment]
Always 19:00 :) https://www.meetup.com/Berlin-Mozilla-Meetup/events/239332143/

**Pull request merged**
