### PR TITLE
Nov 09 2017 meetup

### PR DESCRIPTION
**Pull request by dmichl**
Second meetup event, ready to roll

### CODE REVIEW

**Comment by tessgadwa** [comment]
Great, I'll be in town then. When and where?

On Nov 3, 2017 5:21 AM, "Dina Michl" <notifications@github.com> wrote:

Second meetup event, ready to roll
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/opensourcedesign/events/pull/91
Commit Summary

   - Nov 09 2017 meetup

File Changes

   - *A* _posts/2017-11-09-open-source-design-nyc.md
   <https://github.com/opensourcedesign/events/pull/91/files#diff-0> (24)

Patch Links:

   - https://github.com/opensourcedesign/events/pull/91.patch
   - https://github.com/opensourcedesign/events/pull/91.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/opensourcedesign/events/pull/91>, or mute the thread

**Comment by dmichl** [comment]
@tessgadwa, 11/09 - thoughtworks at 6pm, come, I  psyched to meet you!!

**Comment by tessgadwa** [comment]
Awesome. I might be late, but I'll do my total best to swing by. It's in
Manhattan, I presume?

**Review by jancborchardt — APPROVED** [review]
Looks good, awesome! :)

**Comment by jancborchardt** [comment]
Good stuff @dmichl! :)

I also wanted to add you to our Twitter account via Tweetdeck but got this:
screenshot from 2017-11-03 14-14-04
Not sure which settings those are, but check it out, and if you adjust it I can add you so you can use Tweetdeck to also Tweet/retweet the event from our opensrcdesign account :)

**Comment by dmichl** [comment]
@jancborchardt I just saw your comment about my privacy settings, I'm going to look into it today and let you know, thanks so much for the heads up and sorry for not seeing this until now :)

**Comment by dmichl** [comment]
ok i fixed my privacy settings. @jancborchardt do you mind trying again?

**Pull request merged**
