### PR TITLE
Fosdem 2016

### PR DESCRIPTION
**Pull request by Xaviju**

### CODE REVIEW

**Comment by Xaviju** [comment]
https://fosdem.org/2016/news/2015-07-08-dates-fosdem-2016/

**Comment by jancborchardt** [comment]
Ideally we will have a devroom again like last year. :) cc @belenbarrospena @yoroy @ei8fdb @lewisnyman

**Comment by belenbarrospena** [comment]
I agree we should go for another one. I don't think the organising is that much effort if we split the work between a few people like we did last year, and a lot of goodness came out of it!

Someone in the IRC channel has suggested something like a design clinic too: a place with some designers where developers can drop in and get some advice. Just something to consider, I guess.

**Comment by Xaviju** [comment]
I will not miss fosdem this year, so if I can help with the organisation or anything else, Ill be happy to help. :smile:

**Comment by belenbarrospena** [comment]
Thanks @Xaviju. Good to have an extra pair of hands!

**Comment by elioqoshi** [comment]
I will be there too (was the last 2 editions and didnt even know about the Open Source Design Initative!) Do you plan to go with your own budget or are there are any opportunities for sponsorship? I might be sponsored by Mozilla but just making sure.

**Comment by jancborchardt** [comment]
@belenbarrospena do you remember when the call for proposals for the devrooms started last year? Isn’t open yet it seems.

@elioqoshi some go with their own budget, some get their travel reimbursed by their projects (I’m with [ownCloud](https://owncloud.org) for example). Cool that you’re in! :)

**Comment by belenbarrospena** [comment]
@jancborchardt the call for devrooms hasn't open yet, but it should do pretty soon. I'm subscribed to the FOSDEM mailing list, so I'll let you all know via the IRC channel when the call opens. 

The other thing that has been discussed was some kind of 'design help desk' where people can drop by with their projects and talk to a designer about them. This is not strictly a booth in the standard FOSDEM way, so if we really want to do something like this, we should probably contact the organisers soon to see what they suggest. Maybe they can provide a table somewhere, or we just take over a couple of tables in the main cafe place, which has loads of space. 

Now, this will require some commitment from designers to be on duty in the help desk, so it can only be done if we gather enough hands.

**Comment by jancborchardt** [comment]
Yeah, that would be cool! I did a session similar to that at Libre Graphics Meeting. I’m definitely in for a »Design help desk« :)

**Comment by belenbarrospena** [comment]
@jancborchardt do you want to kick off the discussion on the IRC channel? Let's see how many designers we can gather :)

**Comment by una** [comment]
@jancborchardt I love the idea of a Design Help Desk!! That's such a great idea for free little consultations and contributions. :+1: Sounds like this is going to be awesome!

**Comment by belenbarrospena** [comment]
so, if you know you will be at FOSDEM and you would be willing to commit some time to the design help desk, please put your names down in this threat, so that we can get an idea of how many people will be around, and if we have enough to actually do it!

**Comment by belenbarrospena** [comment]
I meant thread, of course :/

**Comment by plastelina** [comment]
@belenbarrospena I'm threatening with my presence :), but seriously. I will be around and I'm happy to help (help desk or/and organising stuffs)

**Comment by belenbarrospena** [comment]
@plastelina great threat ;) One more pair of hands for the list. 

Anybody else interested in helping with the FOSDEM devroom + design help desk?

**Comment by pablocubico** [comment]
Great news! I'll be at FOSDEM hopefully, as last year, I'll be glad to help with anything.

In this year's edition, I arrived on the final day but next one I'll make sure to be there earlier, maybe staying for a few days in Brussels.

**Comment by belenbarrospena** [comment]
@pablocubico excellent. Thanks, Pablo!

**Comment by ei8fdb** [comment]
I’m happy to help out at the design desk for a morning or afternoon, and then also at dev room.

**Comment by jancborchardt** [comment]
Awesome! :) This’ll be even better than last time!

**Comment by ghost** [comment]
Subscribe :-) Design desk sounds like fun!

**Comment by Xaviju** [comment]
As I said before, I am open to help with anything, at the design desk and organizing stuff. It would be nice to create a mailing list (or anything else) of interested people in the design devroom and if @belenbarrospena needs help could ask for it and assign tasks.

**Comment by jancborchardt** [comment]
I’d say since we already use Github, having an issue for FOSDEM here or a new repo for it is much simpler and more public than creating a mailing list. :)

**Comment by simonv3** [comment]
(I'm not going but I've heard complaints from people who are members of open source design that there's too many repos and they don't like the spam, just FYI)

**Comment by raucao** [comment]
People can easily unwatch repos anytime. Maybe it would help to explain how to do that.

For example, when creating a new repo (which will auto-subscribe all members of the org), you could create a first issue that introduces people to what the repo is about and where the unwatch button is.

**Comment by ei8fdb** [comment]
+1 for using Github as a mailing list-like function.

I’m replying to this thread from my e-mail! In my head it’s a mailing list :)

Should we start putting together a list of who’ll cover the FOSDEM design desk? By hour? Or is that too much organisation? :)

Bernard

**Pull request merged**
