### PR TITLE
add Open Source Design track at FOSDEM from the past

### PR DESCRIPTION
**Pull request by jancborchardt**
Please review @belenbarrospena @yoroy @lewisnyman @ei8fdb! :)

Also check out the cool events page we already have: http://opensourcedesign.net/events/

### CODE REVIEW

**Comment by jancborchardt** [comment]
@Xaviju @bnvk it would be cool if we don’t have to repeat the date, time and location every time from the header into the content. Instead it should be inserted into the detail view from the header, right?

**Comment by simonv3** [comment]
@jancborchardt yeah this is unnecessary data duplication. Do you want to update it right now or just create an issue for it and we can slowly fix it over time?

**Comment by jancborchardt** [comment]
Thanks @bnvk for creating #15 for that.

How do these additions look, did anyone review?

**Comment by simonv3** [comment]
Yeah, I was just wondering whether you wanted to apply that in your current PR or not. I'll merge :)

**Comment by jancborchardt** [comment]
Thanks! :)

**Pull request merged**
