### PR TITLE
Add FOSDEM 2018 event

### PR DESCRIPTION
**Pull request by victoria-bondarchuk**
Used the same announcement template as last year.

### CODE REVIEW

**Comment by victoria-bondarchuk** [comment]
Addresses part of #64

**Review by evalica — APPROVED** [review]

**Comment by evalica** [comment]
@victoria-bondarchuk apparently it didn't work. The extension file needs to be ".md" instead of ".markdown"

**Comment by evalica** [comment]
I reverted the change. Can you change the extension?

**Comment by victoria-bondarchuk** [comment]
Done in #86, thank you!

**Pull request merged**
