### PR TITLE
OSD NYC  Meetup 12/14

### PR DESCRIPTION
**Pull request by dmichl**
upcoming meetup :)

### CODE REVIEW

**Comment by jancborchardt** [comment]
Looks good to me! :) Awesome to see that @toolness will give a presentation on such an important topic!

**Comment by jancborchardt** [comment]
And thank you so much for organizing this so steadily! :)

**Comment by jancborchardt** [comment]
Oh and by the way, for ticketing (cause it's free, right?) we could also use our Open Collective page:
https://opencollective.com/opensourcedesign

We did that for the Summit to gauge attendance. And using OpenCollective would also make people aware of it and maybe donate. :) what do you think @dmichl @simonv3?

**Comment by dmichl** [comment]
@jancborchardt Sounds fine to me! @simonv3 do you know how to set it up?

**Comment by simonv3** [comment]
@dmichl here -> https://opencollective.com/opensourcedesign/events/new

Let me know if you need to be added as a core contributor!

**Comment by dmichl** [comment]
yes please, apparently i can't access unless i'm a core contributor. Thank
you!

**Comment by simonv3** [comment]
@dmichl I'll need your e-mail. You can DM me in the IRC/Riot channel?

**Pull request merged**
