### PR TITLE
Update 2018-05-24-open-source-design-nyc.md

### PR DESCRIPTION
**Pull request by evalica**

### CODE REVIEW

**Review by jancborchardt — APPROVED** [review]
Yup, makes sense :+1:

**Comment by jancborchardt** [comment]
@dmichl @davelab6 is there a next meetup planned already? :)

**Comment by jancborchardt** [comment]
@dmichl @davelab6 @xuv is there a next meetup planned already? :)

**Comment by xuv** [comment]
@jancborchardt kind of. We need to find a date :)

**Comment by jancborchardt** [comment]
@xuv cool! :) Always helps to just make it recurring like every x weekday of the month, like we do every first Wednesday of the month for the calls. :)

**Pull request merged**
